import { Component } from '@angular/core';
import { ServicesComponent } from '../../components/services/services.component';
import { AnimatedHeadingComponent } from '../../components/animated-heading/animated-heading.component';

@Component({
  selector: 'app-services-page',
  standalone: true,
  imports: [ServicesComponent, AnimatedHeadingComponent],
  templateUrl: './services-page.html',
  styleUrl: './services-page.scss'
})
export class ServicesPage {
  oneDayTours = [
    'ANDIPALAYAM BOATING, GASS MUSEUM, GD SCIENCE MUSEUM, SEMMOZHI POONGA',
    'MARUTHA MALAI, ISHA, GANDHI PARK, SEMMOZHI POONGA',
    'GODIVERI DAM, BHAVANI SAGAR DAM AND PARK, THEN THIRUPATHY',
    'AMARAVATHY DAM, THIRUMOORTHY DAM, ALIYAR DAM, MASANIAMMAN',
    'OOTY PYKARA, 6TH MILE, 7TH MILE, BOTANICAL GARDEN, CHILDRENS PARK BY VAN',
    'KODAIKONAL ROUNDS BY VAN',
    'KURUMBAPATI ZOOLOGICAL PARK, ERGAD (ERGAD BY VAN)',
    'MUNAR ROUNDS BY JEEP',
    'MADURAI, KILADI, VAIGAI DAM',
    'MADURAI, SURULI FALLS, KUTCHANUR TEMPLE, VAIGAI DAM',
    'MADURAI MEENACHI TEMPLE, GANDHI MUSEUM, NAYAKKA MAHALL, ALAGAR TEMPLE',
    'RAMESWARAM, ARISAL MUNAI (DHANUSKODI), ABDUL KALAM MEMORIAL HALL AND HOUSE, PAMBAN BRIDGE',
    'THANJAVUR TEMPLE, PALACE, SIVAGANGAI POONGA, KALLANAI',
    'VELANKANNI, THIRUNALLARU, THARANGAMPADI PALACE, POOMBKAR BEACH',
    'CHIDAMBARAM, PITCHAVARAM, THARANGAMPADI, BOOMBUKAR',
    'GANGAIKONDASOZHAPURAM TEMPLE, POOMBUKAR, THARAGAMBADI',
    'THANJAVUR, VELANKANNI',
    'THIRUCHY PLANITORIUM, BUTTERFLY PARK, KALLANAI, BIRDS PARK',
    'ATHIRAMPALLY FALLS, THIRUSSUR ZOO, MALAMPUZHA DAM'
  ];

  twoDayTours = [
    'KANNIYAKUMARI VIVEKANANDHA ROCK AND MIRROR BRIDGE BY BOAT, THIRUPARAPPU FALLS, MATHUR THOTTIPALAM, PADMANABHAPURAM PALACE, MUTTAM BEACH',
    'CHENNAI ROUNDS = CHENNAI CENTRAL MUSEUM, PLANETARIUM, SNAKE PARK, VANDALUR ZOO, DAKSHINA CHITRA HERITAGE MUSEUM, MAHABULIPURAM BEACH, PANCHA RATHAS',
    'BANGALORE, ISRO, VISVESVARAYA MUSEUM, ISKON TEMPLE, WONDERLA',
    'MYSORE PALACE, ZOO, SAMUNTRY HILL TEMPLE, KRS BRINDHAVAN DAM, GRS FANTASY PARK AND SNOW PARK',
    'MYSORE PALACE, ZOO, SAMUNTRY HILL TEMPLE, KRS BRIDHAVAN DAM, MYSORE THIRUPATHY, TIPPU MEMORIAL HALL, SANGAMAM',
    'OOTY ROUNDS',
    'COCHIN AND WONDERLA',
    'MUNAR, COCHIN',
    'MUNAR, WONDERLA',
    'THIRUVANANDHAPURAM ZOO, ISRO, POOVAR BOATING, KOVALAM BEACH, THIRUPARAPPU FALLS',
    'THIRUVANADHAPURAM ZOO, ISRO, POOVAR BOATING, ANY ONE BEACH, JATAYU EARTH CENTRE, VARKALA CLIFF, BLOCK SAND BEACH, VARKALA BEACH, MANGROVE FOREST BOATING',
    'THENMALA DAM, THIRUVANADHAPURAM ROUNDS',
    'SRI HARI KOTTA ISRO, (WITH PERMISSION) MAHABULIPURAM, PITCHAVARAM',
    'VAGAMON JEEP RIDE, COCHIN',
    'VAGAMON, WONERLA',
    'VAGAMON, THEKKADY',
    'VAYANADU ROUNDS',
    'OOTY, MASANAMGUDI',
    'MYSORE, BHANDHIPUR FOREST, OOTY',
    'BHANDHIPUR FOREST, MASANAMFUDI, OOTY ROUNDS'
  ];
}
